source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "webrick"
gem "jekyll-theme-so-simple"
gem "csv"
gem "base64"